services:
  smtm-api:
    container_name: smtm-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - APP_ENV=development
      - PORT=5000
      - LOG_LEVEL=${LOG_LEVEL}
      - XERO_BASE_URL=${XERO_BASE_URL}
    restart: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: smtm-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - smtm-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
